spring:
  application:
    name: regist_center

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    hostname: localhost  
